version: "2.1"
services:
  ssh:
    image: ghcr.io/linuxserver/openssh-server
    container_name: openssh-server
    hostname: openssh-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - PUBLIC_KEY_FILE=/config/ssh_host_keys/ssh_host_rsa_key.pub
      - SUDO_ACCESS=false
      - PASSWORD_ACCESS=false
      - USER_NAME=linuxserver
    volumes:
      - ./ssh-server-config:/config/ssh_host_keys:ro
    ports:
      - "127.0.0.1:2223:2222"
    networks:
      - inner

  httpbin:
    image: "kennethreitz/httpbin"
    networks:
      inner:
        ipv4_address: 10.5.0.5

networks:
  inner:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
